# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  require Pod::Executable.execute_command(
    'node',
    ['-p', "require.resolve('#{script}', {paths: ['#{__dir__}']})"]
  ).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
  RNFirebaseAsStaticFramework = true
end

setup_permissions([
  'LocationAlways',
  'LocationWhenInUse',
  # 'LocationAccuracy', # optional
])

target 'evolve' do
  config = use_native_modules!
  flags = get_default_flags()

  # ✅ Firebase pods
  pod 'Firebase/Messaging'
  pod 'Firebase',               :modular_headers => true
  pod 'FirebaseCoreInternal',   :modular_headers => true
  pod 'GoogleUtilities',        :modular_headers => true
  pod 'FirebaseCore',           :modular_headers => true
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
        installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['OTHER_LDFLAGS'] ||= []
        config.build_settings['OTHER_LDFLAGS'] << '-ObjC'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
     installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
