import {createBox, createText, useTheme as useReTheme} from '@shopify/restyle';

export const theme = {
  colors: {
    apptheme: '#FF5F2D',
    white: '#fff',
    screen: '#FAFAFA',
    black: '#131313',
    error: '#FB3766',
    success: '#11CF8B',
    input: '#F3F4F6',
    placeholder: '#949494',
    yellow: '#F9F248',
    lighyellow: '#D3FE8A',
    green: '#56E39F',
    red: '#FF5574',
    lunch: '#4482C3',
    dinner: '#73AC12',
    cancel: '#FF455B',
    lightGreen: '#D0F81D',
    softGray: '#E8E9F0',
    mediumGray: '#BFC2CF',
    lightGray: '#F5F5F6',
    gray: '#686C83',
    darkGray: '#1D1617',
    rank: '#FFA017',
    second: '#2572E8',
  },
  spacing: {
    xxs: 3,
    xs: 6,
    s: 8,
    sm: 12,
    m: 16,
    ml: 20,
    l: 24,
    xl: 40,
    xxl: 50,
  },
  borderRadii: {
    s: 4,
    m: 10,
    l: 25,
    xl: 40,
  },
  textVariants: {
    unbounded20black_bold: {
      fontSize: 20,
      lineHeight: 24,
      color: 'black',
      fontFamily: 'Unbounded-Bold',
    },
    unbounded20black_semibold: {
      fontSize: 20,
      lineHeight: 24,
      color: 'black',
      fontFamily: 'Unbounded-SemiBold',
    },
    unbounded20black_medium: {
      fontSize: 20,
      lineHeight: 24,
      color: 'black',
      fontFamily: 'Unbounded-Medium',
    },
    unbounded20black_regular: {
      fontSize: 20,
      lineHeight: 24,
      color: 'black',
      fontFamily: 'Unbounded-Regular',
    },
    poppins32black_bold: {
      fontSize: 32,
      lineHeight: 34,
      color: 'black',
      fontFamily: 'Poppins-Bold',
    },
    poppins32black_semibold: {
      fontSize: 32,
      lineHeight: 34,
      color: 'black',
      fontFamily: 'Poppins-SemiBold',
    },
    poppins32black_medium: {
      fontSize: 32,
      lineHeight: 34,
      color: 'black',
      fontFamily: 'Poppins-Medium',
    },
    poppins32black_regular: {
      fontSize: 32,
      lineHeight: 34,
      color: 'black',
      fontFamily: 'Poppins-Regular',
    },
    poppins12black_bold: {
      fontSize: 12,
      lineHeight: 16,
      color: 'black',
      fontFamily: 'Poppins-Bold',
    },
    poppins12black_semibold: {
      fontSize: 12,
      lineHeight: 16,
      color: 'black',
      fontFamily: 'Poppins-SemiBold',
    },
    poppins12black_medium: {
      fontSize: 12,
      lineHeight: 16,
      color: 'black',
      fontFamily: 'Poppins-Medium',
    },
    poppins12black_regular: {
      fontSize: 12,
      lineHeight: 16,
      color: 'black',
      fontFamily: 'Poppins-Regular',
    },
    poppins14black_bold: {
      fontSize: 14,
      lineHeight: 18,
      color: 'black',
      fontFamily: 'Poppins-Bold',
    },
    poppins14black_semibold: {
      fontSize: 14,
      lineHeight: 18,
      color: 'black',
      fontFamily: 'Poppins-SemiBold',
    },
    poppins14black_medium: {
      fontSize: 14,
      lineHeight: 18,
      color: 'black',
      fontFamily: 'Poppins-Medium',
    },
    poppins14black_regular: {
      fontSize: 14,
      lineHeight: 18,
      color: 'black',
      fontFamily: 'Poppins-Regular',
    },
    poppins16black_bold: {
      fontSize: 16,
      lineHeight: 18,
      color: 'black',
      fontFamily: 'Poppins-Bold',
    },
    poppins16black_semibold: {
      fontSize: 16,
      lineHeight: 18,
      color: 'black',
      fontFamily: 'Poppins-SemiBold',
    },
    poppins16black_medium: {
      fontSize: 16,
      lineHeight: 18,
      color: 'black',
      fontFamily: 'Poppins-Medium',
    },
    poppins16black_regular: {
      fontSize: 16,
      lineHeight: 18,
      color: 'black',
      fontFamily: 'Poppins-Regular',
    },
    poppins18black_bold: {
      fontSize: 18,
      lineHeight: 22,
      color: 'black',
      fontFamily: 'Poppins-Bold',
    },
    poppins18black_semibold: {
      fontSize: 18,
      lineHeight: 22,
      color: 'black',
      fontFamily: 'Poppins-SemiBold',
    },
    poppins18black_medium: {
      fontSize: 18,
      lineHeight: 22,
      color: 'black',
      fontFamily: 'Poppins-Medium',
    },
    poppins18black_regular: {
      fontSize: 18,
      lineHeight: 22,
      color: 'black',
      fontFamily: 'Poppins-Regular',
    },
    poppinsTitle20black_bold: {
      fontSize: 20,
      lineHeight: 24,
      color: 'black',
      fontFamily: 'Poppins-Bold',
    },
    poppinsTitle20black_semibold: {
      fontSize: 20,
      lineHeight: 24,
      color: 'black',
      fontFamily: 'Poppins-SemiBold',
    },
    poppinsTitle20black_medium: {
      fontSize: 20,
      lineHeight: 24,
      color: 'black',
      fontFamily: 'Poppins-Medium',
    },
    poppinsTitle20black_regular: {
      fontSize: 20,
      lineHeight: 24,
      color: 'black',
      fontFamily: 'Poppins-Regular',
    },
  },
  breakpoints: {},
};

export type Theme = typeof theme;
export const Box = createBox<Theme>();
export const Text = createText<Theme>();
export const useTheme = () => useReTheme<Theme>();
